apiRules:
- exclude:
    uidRegex: ^System\.Object
    type: Type
- exclude:
    uidRegex: ^Hawf
    type: Namespace
- exclude:
    uidRegex: ^TrackmaniaIo.ApiClient.Resources.TmIoApiBase
    Type: Type
- exclude:
    uidRegex: ^TrackmaniaIo.ApiClient.Utils.ValueConverters
    Type: Namespace
